name: ci

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id  }}
    cancel-in-progress: true
  
on:
    push:
    pull_request:
        branches:
            - main

env:
  CMAKE_GENERATOR: Ninja

permissions:
    contents: read

jobs:
  android:
    env:
      CMAKE_C_COMPILER_LAUNCHER: ccache
      CMAKE_CXX_COMPILER_LAUNCHER: ccache
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        abi: [ arm64-v8a ]
        build_tests: [ "ON" ]
        stl_type: ["c++_shared"]

    steps:
      - uses: actions/checkout@v4
      - uses: lukka/get-cmake@latest
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: android-${{ matrix.abi }}-${{ matrix.build_tests }}-${{ matrix.stl_type }}
      - name: Configure
        run: |
          CFLAGS="$CFLAGS -Ofast" CPPFLAGS="$CPPFLAGS -Ofast" cmake -S . -B build/ --toolchain $ANDROID_NDK_ROOT/build/cmake/android.toolchain.cmake \
          -D ANDROID_PLATFORM=24 \
          -D CMAKE_ANDROID_ARCH_ABI=${{ matrix.abi }} \
          -D CMAKE_ANDROID_STL_TYPE=${{ matrix.stl_type }} \
          -D ANDROID_USE_LEGACY_TOOLCHAIN_FILE=NO \
          -D CMAKE_BUILD_TYPE=Release \
          -D BUILD_TESTS=${{ matrix.build_tests }} \
          -D UPDATE_DEPS=ON \
          -D BUILD_WERROR=ON
      - name: Build
        run: cmake --build build/
      - name: Install
        run: cmake --install build --prefix build/install
      - name: Uplod
        uses: actions/upload-artifact@v4
        with:
          path: build/
